# Generated by Django 3.2.7 on 2021-09-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentythree', '0002_auto_20210915_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
